version: '2.1'

services:
  tomcat:
    image: 'rajusw804/tomcat:v1'
    ports:
      - '8080:8080'
    depends_on:
      - my-mongodb
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
  my-mongoclient:
    # build will get tagged with 'image'
    build: ./my-mongoclient
    image: my-mongoclient
    container_name: my-mongoclient
    environment:
      - MONGO_SERVER=my-mongodb
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - mongo_net
    depends_on:
      - my-mongodb
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
networks:
  mongo_net:
    driver: bridge
